### ISSUE TITLE
Ошибка выполнения запроса

### ISSUE THREAD

**Issue by dronchik** [hungry-devel/MongoCLITool#2]
Доброго времени суток!

Установил проект, тесты все прошли. Решил запустить приложение на своем дампе и при попытке выполнить запрос получил ошибку:
```
MongoCLITool andrew$ php ./bin/eva execute "select * from users"

PHP Notice:  Undefined offset: 0 in /Users/andrew/projects/MongoCLITool/src/TemplateProcessor.php on line 44

Notice: Undefined offset: 0 in /Users/andrew/projects/MongoCLITool/src/TemplateProcessor.php on line 44
PHP Warning:  array_keys() expects parameter 1 to be array, null given in /Users/andrew/projects/MongoCLITool/src/TemplateProcessor.php on line 44

Warning: array_keys() expects parameter 1 to be array, null given in /Users/andrew/projects/MongoCLITool/src/TemplateProcessor.php on line 44
PHP Catchable fatal error:  Argument 1 passed to Symfony\Component\Console\Helper\Table::setHeaders() must be of the type array, null given, called in /Users/andrew/projects/MongoCLITool/src/TemplateProcessor.php on line 30 and defined in /Users/andrew/projects/MongoCLITool/vendor/symfony/console/Helper/Table.php on line 216

Catchable fatal error: Argument 1 passed to Symfony\Component\Console\Helper\Table::setHeaders() must be of the type array, null given, called in /Users/andrew/projects/MongoCLITool/src/TemplateProcessor.php on line 30 and defined in /Users/andrew/projects/MongoCLITool/vendor/symfony/console/Helper/Table.php on line 216
```

Еще один странный момент, в конфигах почему-то задается название коллекции и оно по умолчанию имеет название 'test'. Не совсем понятно, зачем этот параметр, если название коллекции внутри базы данных может быть любое.

**Comment by dronchik** [comment]
Наверное, еще было бы неплохо более красиво пользователю говорить, что он не так сделал, а то как-то совсем не комильфо. Ну тесты подправить, чтоб они не только позитивные случаи делали.

**Comment by hungry-devel** [comment]
Доброе утро, @dronchik 
По поводу обработки исключений и валидации данных - согласен, даже более того, я это начал писать, но получились странные костыли и непонятное поведение, из-за особенностей расширения(например MongoClient::selectDB не возвращает исключение в случае неудачи ([документация](http://php.net/manual/en/mongoclient.selectdb.php)), а создает базу данных) из-за этого получились такие же странные тесты..и в конце-концов это выпилилось.
На данный момент, в кач-ве логера используется [Monolog](https://github.com/Seldaek/monolog) который все ошибки пишет в файл /logs/app.log, а пользователь видит сообщение с просьбой проверить запрос и конфигурацию

По поводу названия коллекции в конфигах - согласен с тем, что не надо было его писать в конфиг. Этот параметр используется в скрипте import.php и означает имя коллекции в которую мы будем импортировать дамп.
Перенес в import.php в качестве переменной $collectionName

По поводу тестов - +. Добавить нечего)

По поводу вашей ошибки - рискну предположить(без конфига неясно), что у вас нет коллекции 'users'. Поэтому результирующий массив пустой и хелпер таблицы падает. Дописал туда проверку.
Тестировал на нескольких дампах, все запросы проходят нормально.

Вот так выглядит структура моей таблицы:
![image](https://cloud.githubusercontent.com/assets/15270185/20333868/66d626a4-abbe-11e6-9920-77b8cc1b6100.png)
 
Дампы которые я использовал:
[rest_collection](https://raw.githubusercontent.com/mongodb/docs-assets/primer-dataset/primer-dataset.json) и [zips_collection](http://media.mongodb.org/zips.json)

zips_collection
![zips_collection](https://cloud.githubusercontent.com/assets/15270185/20333639/8e6086da-abbc-11e6-85d0-82dd891c1a1b.gif)

rest_collection
![rest_collection](https://cloud.githubusercontent.com/assets/15270185/20333641/9157f54e-abbc-11e6-8d84-65c9d4f4666b.gif)

Спасибо, что нашли время посмотреть проект и прислали конструктивные замечания.

**Comment by dronchik** [comment]
Спасибо, теперь все завелось и ошибки не сыпятся. 

Пару мелких замечаний:

1. Было бы хорошо, если бы можно было менять локально конфиги и не меня файлы, которые находятся под контролем версий.

2. В ООП основной механизм обработки ошибок это Exception-ы, их не просто удобно использовать, во время тестов так же легче негативные случаи проверять. В целом много профитов от них.

В когде я их нигде не увидел как и try/catch конструкции. Это как правило решает все основные проблемы. Ну и сам php нужно на уровне errorhandling-а конфигурировать для develop и prod режимов по разному.

По best practices обработки ошибок детальней можно почитать вот тут http://www.phptherightway.com/#errors_and_exceptions.

**Comment by hungry-devel** [comment]
@dronchik Cпасибо, почитаю. 
Могу лишь добавить, что проблему с fatal error'ами это не решило бы...в 5.6 просто нет адекватного механизма их отлова, он появился только в 7 версии(и то, не все можно поймать), но вы правы, минимальный набор должен был быть.
